### ISSUE TITLE
您好！关于得分问题

### ISSUE THREAD

**Issue by lonePatient** [Vipning/latest-chinese-ner-model#1]
你在CLUENER榜单上用bilstm-crf跑出了80+的分数，我们用你这代码好像只有68+，能否详细的说下你的方案呢？谢谢！

**Comment by Vipning** [comment]
不好意思哈。这个是我第一次用bilstm+crf的代码，新模型就一直用这个名字和这个的链接了，我一直没换，我的新模型还没更新。
